spring.application.name=LlantasApi
spring.datasource.url=jdbc:postgresql://localhost:5432/db_llantas
spring.datasource.username=postgres
spring.datasource.password=admin
debug=true
spring.profiles.active=dev

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect