spring.application.name=LlantasApi
spring.datasource.url=jdbc:postgresql://localhost:5432/db_llantas
spring.datasource.username=postgres
spring.datasource.password=admin
debug=true
spring.profiles.active=dev
spring.jpa.properties.hibernate.type.json.preferred-json-type-handler=com.vladmihalcea.hibernate.type.json.JsonBinaryType

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true